project:
  type: website
  output-dir: docs

website:
  title: "Data Science for Eco/Evo (Fall 23 BIOE215)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - syllabus.qmd
      - text: "Lessons"
        menu:
          - lessons/01_comp_proj_org.qmd
          - lessons/02_comp_thinking_1.qmd
          - lessons/02b_vectors_key_points.qmd
          - lessons/03_working_data.qmd
      - text: "Discussions"
        menu:
          - discussions/02_open_data_1.qmd
          - discussions/03_open_tools.qmd
          - discussions/04_open_data_2.qmd
      - reporting_errors.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

