project:
  type: website
  output-dir: docs

website:
  title: "Data Science for Eco/Evo (Fall 23 BIOE215)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
#      - syllabus.qmd
#      - resources.qmd
#      - assessment.qmd
      - text: "Lessons"
        menu:
          - lessons/01_comp_proj_org.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

