---
title: "Data Science for Eco/Evo (Fall 23 BIOE215)"
---

Welcome to *Data Science for Eco/Evo*! I'm excited to have you in class and hope this course helps you reach your research goals. On this website, you'll find course logistics, schedule, and lessons. You'll use GitHub for submitting assessments.

## Course

Data Science for Eco/Evo

BIOE215, 3 Credits, Fall 2023

## Instructor

Dr. Max Czapanskiy (he/they)

Email: [mczapans\@ucsc.edu](mailto:mczapans@ucsc.edu)

## Location

CoastBio 115

## Times

Mondays, 3:30-5:30 pm

## Office Hours

Times: Thursdays 3:30-5:30 pm

Location: CoastBio Otter Conference Room

Or by appointment*.*

## Course Description

This course will aim to be practical and provide structure for learning the computational skills most eco/evo grad students have to pick up on their own. Topics will include programming best practices in R, organizing data and computational projects, and planning for reproducibility. This is a chance to gain knowledge and experience with the nuts and bolts of making your science work in code, without trying to learn generalized linear models at the same time. The course structure will be self-directed for weeks 1-6, followed by a final project in weeks 7-10.
